README.md, build.gradle, downloads.gradle, environments.gradle, resources/studio-live/crafter.sh, resources/studio/crafter.sh
=> Refactor Gradle Scrip to adhere new Readme spec

build.gradle, gradle/wrapper/gradle-wrapper.properties, resources/crafter/crafter.sh
Upgrades Gradle to 3.5 as well.
=> Solves #517

environments.gradle
Config folder is already copied to /bin/crafter-deployer and is not used in /data.
=> Removed duplicated config files for crafter-deployer.

build.gradle, resources/crafter/crafter.sh, resources/crafter/setenv.sh, resources/deployer/deployer.sh, utils/src/main/java/org/craftercms/bundle/utils/BundleUtils.java, utils/src/main/java/org/craftercms/bundle/utils/actions/Download.java, utils/src/main/java/org/craftercms/bundle/utils/actions/DownloadMongoDB.java, utils/src/main/java/org/craftercms/bundle/utils/actions/Unzip.java
the spwan process within gradle that outputs `\r` makes gradle crazy and looses the process lock.
=> Solves #890 

environments.gradle, resources/crafter/crafter.sh, resources/crafter/init-site.sh, resources/crafter/setenv.sh, resources/deployer/config/base-target.yaml, resources/tomcat-config-delivery/crafter/engine/extension/rendering-context.xml, resources/tomcat-config-delivery/crafter/engine/extension/server-config.properties, resources/tomcat-config-delivery/crafter/engine/extension/services-context.xml, resources/tomcat-config/crafter/engine/extension/rendering-context.xml
* Did some small script fixes
* Added init-site.sh for the delivery env.
* Added specific Engine configuration for delivery.
=> Bundle fixes:

build.gradle, environments.gradle
Configuration on delivery now only uses filtering and not processing the file with XML or properties API.
=> Solves #912

resources/README.txt
Updates paths under in deployment structure.
=> Solves #902

environments.gradle, resources/crafter/init-site.sh, resources/tomcat-config-delivery/crafter/engine/extension/rendering-context.xml, resources/tomcat-config-delivery/crafter/engine/extension/services-context.xml
* Fixed scripts to setup a site and make multi tenancy delivery work.
=> Delivery changes:

README.md, build.gradle, environments.gradle
Use the property `-Pcrafter.social=true` or `-Pcrafter.profile=true` to make gradle include social and profile artifacts in the deployment.
=> Solves #896 and  #934 different commits

environments.gradle
=> Make delivery script executable

build.gradle, gradle/wrapper/gradle-wrapper.properties
Gradle will fail (and stop) if any sub-process returns a non-zero value.
=> Solves #972

build.gradle
=> Solves #896 

build.gradle
=> Fixed issue when deploying 'all' environments

resources/crafter/crafter.bat, resources/crafter/crafter.sh, utils/src/main/java/org/craftercms/bundle/utils/BundleUtils.java, utils/src/main/java/org/craftercms/bundle/utils/actions/ApiPost.java, utils/src/main/java/org/craftercms/bundle/utils/actions/Unzip.java, utils/src/main/java/org/craftercms/bundle/utils/actions/Zip.java
=> Added backup & restore tasks

resources/crafter/crafter.bat, resources/crafter/crafter.sh
=> Improvements for backup/restore scripts

build.gradle
Bundle Zip's name are crafter-cms-ENV.zip|tar.gz notice that md5 signatures are not generated by the `./gradlew` script
=> Solves 1165

resources/crafter/crafter.bat, resources/crafter/crafter.sh
=> Updated default name for backup files

resources/tomcat-config-delivery/crafter/engine/extension/server-config.properties, resources/tomcat-config/crafter/engine/extension/server-config.properties
* Added missing Profile URL to Authoring and Engine server-config.properties.
=> Engine config fixes:

resources/crafter/crafter.bat, resources/crafter/crafter.sh
=> Prevent restore process on a running environment.

build.gradle
=> Adding pending Test Suites (xml files) to run all the automated test cases for (API & Studio UI)

resources/crafter/crafter.bat, resources/crafter/crafter.sh
=> Moved backup files to a subfolder instead of the root.

resources/crafter/crafter.sh
=> Fixed backup folder creation.

build.gradle, resources/crafter/crafter-setenv.bat, resources/crafter/crafter-setenv.sh, resources/crafter/crafter.bat, resources/crafter/crafter.sh
Also:
Profile Server is not build if not needed
Startup script will check for OS current arch (32 vs 64) if 32 will throw a waring and die.
=> Fixes 1231, also adds arch check

build.gradle
Depending on merge of https://github.com/craftercms/test-suite/pull/128
=> Added new Sanity Test Suite file to execute

environments.gradle
=> Removed unnecessary folder (it is created on startup if needed)

resources/crafter/crafter.sh
https://github.com/craftercms/craftercms/issues/1243
=> Fixes for crafter.sh script

build.gradle, environments.gradle
Some Reformat some code.
New param name is `crafter.testing.suites` send a list of relative to the `test-suite` project or  full path , multiple files can be send if added the `,` between the paths
=> Solves #1449

resources/crafter/crafter.bat, resources/crafter/crafter.sh
=>  Restore now wipes existing data before starting

resources/crafter/crafter.bat
=> Fix to prevent the terminal from closing after running the script

resources/crafter/crafter.bat, resources/crafter/crafter.sh
=> Added db installation to restore task

resources/crafter/crafter.bat, resources/crafter/crafter.sh
=> Fixed db restore in windows

resources/crafter/crafter.bat, resources/crafter/crafter.sh
=> Cleaned up backup/restore scripts

environments.gradle, resources/crafter/crafter.sh
=> Solves #1546

resources/crafter/crafter.bat, resources/crafter/init-site.bat, resources/crafter/init-site.sh
=> Added ssh private key to init script

utils/src/main/java/org/craftercms/bundle/utils/actions/Zip.java
=> Added excluded extensions for backups

build.gradle
* Solves #1329 
* Added 30 sec delay to before start the test so authoring can test
* Change all `println` to `logger.lifecycle` this will prevent messages
been written after they were intended due  threading and terminal locking. 
also this add the availability to make quiet builds using `-q` 
* Some formatting issues fixes as well.
=> Solves #1329

build.gradle, environments.gradle, resources/crafter/crafter-setenv.sh, resources/crafter/crafter.sh, resources/crafter/crafter.sh.1, resources/crafter/init-site.bat
Also:
* Adds a man page for `crafter.sh` script that documents all prams and variables of the script
* Adds a `-v | --version` to the script to make it easy document any issue.
* Make  exit codes to be different  per case so it's easy to debug the reason of failure `$?`
* Adds Studio and Deployer version (and git commit Id) to the result of `status` 
* Adds a `done` in the end of `init-script.bat`
=> Solves #1539

environments.gradle, resources/crafter/crafter.sh
Also:
* Fix a minor string issue on Studio Status when its down.
=> Solves 1599

resources/crafter/crafter.bat, resources/crafter/crafter.sh
=> Added new validations to backup task

resources/crafter/crafter.bat, resources/crafter/crafter.sh, resources/crafter/init-site.sh
=> Updates for scripts

utils/src/main/java/org/craftercms/bundle/utils/actions/ApiPost.java
https://github.com/craftercms/craftercms/issues/1601
=> Added CSRF cookie & token for API calls

resources/crafter/init-site.bat, resources/crafter/init-site.sh
=> Fixes for init-site scripts

build.gradle
=> Check the downloads regardless the status of the environments folder.

resources/crafter/init-site.sh
* Fixed several problems with init-site.sh, mainly the problem with just calling it with one param (fix for craftercms/craftercms#1605)
=> init-site.sh fixes:

resources/crafter/init-site.bat
https://github.com/craftercms/craftercms/issues/1605
=> Fixed init-site.bat script to match the unix version

resources/crafter/init-site.bat, resources/crafter/init-site.sh
https://github.com/craftercms/craftercms/issues/1697
=> Fixed init-site scripts to use environment variables

resources/crafter/init-site.bat
=> Fixed repo validation in init-site.bat script

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Add security type setting to the studio config override yaml file #1744
=> Add security type setting to the override yaml file #1744

.gitignore, build.gradle
Should not block the terminal in windows
Solves #1749
=> Changes the way the output is written/read

.gitignore, build.gradle
https://github.com/craftercms/craftercms/issues/1741
=> Added tasks for plugins

build.gradle
Changed the execution order to:
-testngAPI.xml
-testng.xml
-testngcomplexscenarios.xml
-testngSanityTest.xml
=> Changed the test cases suite order to execute first the API test cases

resources/migration/migrate.sh
* Added some additional comments.
=> Fix for 1806:

build.gradle, downloads.gradle
Added support for IE `-Pcrafter.testing.browser`
Support for Edge browser on Windows 10 Fall Creators update.
=> Solves #1767 

build.gradle
=> Solves #1770

build.gradle
Added changes to user baseurl for delivery test and for execution of scripts (when the properties file is autogenerated)
=> Added new execution values for test when test-properties file is generated

build.gradle, resources/crafter/init-site.bat
Change the way relative paths are calculated. 
Also, check that the folder given is a git repo.
=> Solves #1882

resources/migration/migrate.sh
* Fixed location to where configured lists where copied.
Ticket craftercms/craftercms#1899
=> Configured lists import fix:

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Update studio overrides to support configurable sandbox branch
https://github.com/craftercms/craftercms/issues/1907
=> CRAFTERCMS-1907

environments.gradle, resources/migration/import-bg.sh, resources/migration/import.sh, resources/migration/migrate-bg.sh, resources/migration/migrate.sh, resources/migration/setenv.sh
* Commits are now done in chunks.
* Actual migration is done in the background.
* Separated import from migration.
Ticket: craftercms/craftercms#1917
=> Migration enhacements

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Added default site id for LDAP security provider to overrides
https://github.com/craftercms/craftercms/issues/1947
=> CRAFTERCMS-1947

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Add studio.db.socket to studio-config-override.yaml #1949
=> Add studio.db.socket to studio-config-override.yaml #1949

build.gradle
Changed version for chrome driver when downloads (latest version of chrome web browser and chrome driver) on build.gradle
=> Added new chrome driver version to cover updates to chrome v64 - 66

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Generated random string for salt overrides
https://github.com/craftercms/craftercms/issues/1930
=> CRAFTERCMS-1930

resources/migration/resources/site-template/config/studio/administration/site-config-tools.xml
Ticket craftercms/craftercms#1973
=> Updated site-config-tools.xml

resources/crafter/crafter.bat, resources/crafter/crafter.sh, utils/src/main/java/org/craftercms/bundle/utils/actions/ApiPost.java
=> Fixed issue with sync api call during backup restore

resources/crafter/crafter.sh
=> Fix for utils jar path

resources/migration/migrate-bg.sh
#2011 
Changes for `sed` on mac:
- `-i` flag requires an argument. `-i ''` is equivalent to `-i` alone on the GNU version
- `-r` needs to be replaced with `-E`
=> Fixed support for sed on mac

resources/crafter/crafter.bat
=> Fix for windows startup script

resources/migration/import-bg.sh, resources/migration/setenv.sh
* Response status and body from Studio API calls are now logged.
* The CSRF API call changed to use status API.
Ticket craftercms/craftercms#2022
=> Import script now provides more info on API calls:

build.gradle, downloads.gradle, environments.gradle
=> Updated gradle scripts to use a specific version of MariaDB4j

README.md, resources/README.txt
Add note to readme files that scripts use `lsof` for linux users and may need to be installed #2031
=> Add note to readme files that scripts use lsof for linux users #2031

environments.gradle, resources/crafter/remove-site.bat, resources/crafter/remove-site.sh
=> Added script to remove a site from a delivery environment

resources/tomcat-config-delivery/setenv.sh, resources/tomcat-config/setenv.sh
https://github.com/craftercms/craftercms/issues/2032
=> Updated tomcat config to override default umask value

build.gradle, downloads.gradle, environments.gradle
When calling the deploy task, the groovy zip will now be downloaded and copied under the bin dir.
Ticket craftercms/craftercms#2089
=> Added Groovy binary:

resources/crafter/init-site.bat, resources/crafter/init-site.groovy, resources/crafter/init-site.sh
* Added init-site.groovy. The shell script and the bat now call the groovy script.
Ticket craftercms/craftercms#1983
=> Added init-site.groovy:

build.gradle, downloads.gradle
* Upgraded Solr version to 6.6.3.
Ticket craftercms/craftercms#2097
=>  Upgraded Solr version:

build.gradle
https://github.com/craftercms/craftercms/issues/2123
=> Manually terminate subprocesses to fix missing output issue

resources/crafter/crafter.bat
https://github.com/craftercms/craftercms/issues/2154
=> Fix to prevent solr from pausing tomcat startup

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Added overrides for ldap site id extraction
https://github.com/craftercms/craftercms/issues/2150
=> CRAFTERCMS-2150

environments.gradle, resources/crafter/init-site.groovy, resources/crafter/remove-site.bat, resources/crafter/remove-site.groovy, resources/crafter/remove-site.sh
Ticket craftercms/craftercms#2175
=> Refactored remove-site script as a Groovy script.

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Support publishing to lower environments as waypoints on the path to Live - overrides configuration
https://github.com/craftercms/craftercms/issues/2176
=> CRAFTERCMS-2176

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Added property for siteId.groupName match index and fixed default property values.
Ticket craftercms/craftercms#2150
=> Added property for siteId.groupName match index

environments.gradle
https://github.com/craftercms/craftercms/issues/2194
=> Fixed file system path for windows

build.gradle
Changed the chrome driver version for latest to download on test suite execution.
=> Upgrading the chrome driver version to latest (2.40) for test-suite.

build.gradle
https://github.com/craftercms/craftercms/issues/2211
=> Upgrading dependencies

build.gradle
https://github.com/craftercms/craftercms/issues/2211
=>  Upgraded mariaDB4j version

build.gradle
Added new test suites to build.gradle file (we separated the testng.xml full suite in multiple subsuites according with integration test document)
=> Added new test suites to build.gradle file.

build.gradle
https://github.com/craftercms/craftercms/issues/2237
=> Updated mariadb4j version

environments.gradle, resources/crafter/grapeConfig.xml
https://github.com/craftercms/craftercms/issues/2241
=> Added grape config file

resources/crafter/crafter.sh
https://github.com/craftercms/craftercms/issues/2222
=> Fix to prevent checking mariadb port on delivery env

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Configuration update
https://github.com/craftercms/craftercms/issues/2201
=> CRAFTERCMS-2201

build.gradle
Ticket craftercms/craftercms#2307
=>  Updated Solr version to 6.6.5

resources/migration/migrate-bg.sh
https://github.com/craftercms/craftercms/issues/2288
=>  Add warning about working copies during site migration

resources/migration/migrate-bg.sh
https://github.com/craftercms/craftercms/issues/2288
=> Add warning about working copies during site migration

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
removed unused properties
https://github.com/craftercms/craftercms/issues/2448
=> CRAFTERCMS-2448

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Ticket craftercms/craftercms#2470
=> Added new SSO logout properties to studio-config-override.yaml

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Ticket craftercms/craftercms#2500
=> Added new SSO logout config properties.

build.gradle
Added latest version of Chrome driver (2.42) to be downloaded.
Also added some missing test suites for full execution.
=> Added latest version of Chrome driver (2.42) to be downloaded.

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Update studio overrides to add authentication chain
https://github.com/craftercms/craftercms/issues/2529
=> CRAFTERCMS-2529

build.gradle
https://github.com/craftercms/craftercms/issues/2615
=> Add new studio ui module

build.gradle
https://github.com/craftercms/craftercms/issues/2615
=> Fix tasks for new ui module

build.gradle
https://github.com/craftercms/craftercms/issues/2253
depends on https://github.com/craftercms/search/pull/118
=> Upgrade Solr to 7.5.0

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
https://github.com/craftercms/craftercms/issues/2580
=> Configuration changes

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Update configuration
https://github.com/craftercms/craftercms/issues/2580
=> CRAFTERCMS-2580

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
https://github.com/craftercms/craftercms/issues/2674
=> Add new CORS properties to studio override config

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Clean up configuration
https://github.com/craftercms/craftercms/issues/2613
=> CRAFTERCMS-2613

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Fixed socket path
https://github.com/craftercms/craftercms/issues/2730
=> CRAFTERCMS-2730

resources/tomcat-config-delivery/catalina.policy, resources/tomcat-config/catalina.policy
Ticket craftercms/craftercms#2701
=> Added permissions needed when changing data and/or logs dir.

build.gradle, downloads.gradle, environments.gradle, resources/tomcat-config-delivery/catalina.policy, resources/tomcat-config/catalina.policy
Ticket craftercms/craftercms#2761
=> Added permissions for java.io.tmpdir.

resources/tomcat-config-delivery/catalina.policy, resources/tomcat-config/catalina.policy
=> Fixed MBean permissions.

resources/crafter/crafter.bat, resources/crafter/crafter.sh, utils/pom.xml, utils/src/main/java/org/craftercms/bundle/utils/Action.java, utils/src/main/java/org/craftercms/bundle/utils/BundleUtils.java, utils/src/main/java/org/craftercms/bundle/utils/actions/ApiPost.java, utils/src/main/java/org/craftercms/bundle/utils/actions/Download.java, utils/src/main/java/org/craftercms/bundle/utils/actions/DownloadMongoDB.java, utils/src/main/java/org/craftercms/bundle/utils/actions/DownloadMongoMSIDB.java, utils/src/main/java/org/craftercms/bundle/utils/actions/Unzip.java, utils/src/main/java/org/craftercms/bundle/utils/actions/Zip.java
Ticket craftercms/craftercms#2769
=> Refactored/fixed backup/restore

resources/crafter/crafter.bat
Ticket craftercms/craftercms#2769
=> Fixed mongo zip download an extract

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Configuration for cluster garbage collection and inactivity indication
https://github.com/craftercms/studio/pull/1431
=> CRAFTERCMS-2691

utils/src/main/java/org/craftercms/bundle/utils/Action.java, utils/src/main/java/org/craftercms/bundle/utils/BundleUtils.java, utils/src/main/java/org/craftercms/bundle/utils/OsCheck.java, utils/src/main/java/org/craftercms/bundle/utils/actions/ApiPost.java, utils/src/main/java/org/craftercms/bundle/utils/actions/Download.java, utils/src/main/java/org/craftercms/bundle/utils/actions/DownloadMongoDB.java, utils/src/main/java/org/craftercms/bundle/utils/actions/DownloadMongoMSIDB.java, utils/src/main/java/org/craftercms/bundle/utils/actions/Unzip.java, utils/src/main/java/org/craftercms/bundle/utils/actions/Zip.java
=> Copyright updated

resources/crafter/crafter.bat, resources/crafter/crafter.sh
Fixed backup so that it can dump the SQL DB even if the dbms folder doesn't exist (typically after upgrade)
=> Fixed backup

resources/tomcat-config-delivery/catalina.policy, resources/tomcat-config/catalina.policy
=> Added additional policy permissions.

build.gradle, environments.gradle
Depends on https://github.com/craftercms/search/pull/132
=> Update for search refactoring

resources/tomcat-config-delivery/catalina.policy, resources/tomcat-config/catalina.policy
Ticket https://github.com/craftercms/craftercms/issues/2800
=> Added new permission properties specific to Studio.

build.gradle
https://github.com/craftercms/craftercms/issues/2829
=> Upgrade ElasticSearch to 6.6.0

docker/compose/crafter_authoring/docker-compose.yml, docker/compose/crafter_delivery/docker-compose.yml, docker/compose/diskless/s3/crafter_delivery/docker-compose.yml, docker/images/authoring/tomcat/Dockerfile, docker/images/delivery/tomcat/Dockerfile, docker/images/deployer/Dockerfile, resources/tomcat-config-authoring/catalina.policy, resources/tomcat-config-delivery/catalina.policy
Ticket craftercms/craftercms#2727
=> Changed Tomcat images to use tomcat:8.5.38-slim.

environments.gradle
https://github.com/craftercms/craftercms/issues/2868
=> Disable cluster discovery for ElasticSearch

build.gradle, downloads.gradle
https://github.com/craftercms/craftercms/issues/2886
=> Upgrade Solr to v7.7.1

resources/tomcat-config-authoring/crafter/search/extension/logging.xml, resources/tomcat-config-delivery/crafter/search/extension/logging.xml
https://github.com/craftercms/craftercms/issues/2897
=> Add logging configuration for crafter-search

resources/bin/crafter.sh
https://github.com/craftercms/craftercms/issues/2875
=> Update monitoring API

resources/env/authoring/tomcat-config/catalina.policy, resources/env/delivery/tomcat-config/catalina.policy
https://github.com/craftercms/craftercms/issues/2912
=> Add permission needed for Groovy Grapes

build.gradle, docker/images/authoring/tomcat/Dockerfile, docker/images/delivery/tomcat/Dockerfile, resources/bin/crafter.sh, resources/env/delivery/bin/crafter-setenv.sh
* Build properties are now converted to the correct type.
* Docker builds now copy the Tomcat setenv.sh.
* On shutdown, now there's a wait of up to 10 secs to kill Tomcat.
=> Several fixes:

docker/images/authoring/tomcat/Dockerfile, docker/images/authoring/tomcat/docker-entrypoint.sh, docker/images/delivery/tomcat/Dockerfile, docker/images/delivery/tomcat/docker-entrypoint.sh, docker/images/deployer/Dockerfile, docker/images/deployer/docker-entrypoint.sh, docker/images/git_ssh_server/Dockerfile, docker/images/git_ssh_server/docker-entrypoint.sh, environments.gradle, resources/bin/crafter.sh
* Refactored Docker wrapper scripts to be actual entrypoints.
* Added backup/restore commands to the entrypoints.
* Did some enhancements to the backup/restore code in crafter.sh.
=> Docker enhancements

resources/env/authoring/tomcat-config/crafter/studio/extension/logging.xml
https://github.com/craftercms/craftercms/issues/3024
Depends on https://github.com/craftercms/engine/pull/256
=> Add CircularQueueLogAppender for studio

docker/images/deployer/docker-entrypoint.sh
=> Added missing SSH fix for Deployer Docker.

build.gradle, docker/images/authoring/tomcat/Dockerfile, docker/images/authoring/tomcat/docker-entrypoint.sh, resources/bin/crafter.sh, resources/bin/crafter.sh.1, resources/deployer/config/base-target.yaml, resources/deployer/deployer.sh, resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/profile/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/profile/management/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/search/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/social/extension/social.properties, resources/env/authoring/tomcat-config/crafter/social/management/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml, resources/env/authoring/tomcat-config/setenv.sh, resources/env/delivery/bin/crafter-setenv.sh, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/delivery/tomcat-config/crafter/engine/extension/services-context.xml, resources/env/delivery/tomcat-config/crafter/profile/extension/server-config.properties, resources/env/delivery/tomcat-config/crafter/profile/management/extension/server-config.properties, resources/env/delivery/tomcat-config/crafter/search/extension/server-config.properties, resources/env/delivery/tomcat-config/crafter/social/extension/social.properties, resources/env/delivery/tomcat-config/crafter/social/management/extension/server-config.properties, resources/env/delivery/tomcat-config/setenv.sh
* Now URLs can be change through env variables (eg Elasticsearch URL)
* Changed webapp related URLs to always point to localhost (since the webapps will be in the same Tomcat)
=> Config enhancements:

README.md
=> Update readme #3045

build.gradle, downloads.gradle
Remove windows references that were needed by [test-suite]
=> Remove windows driver references and update chromedriver version

utils/src/main/resources/classes/org/craftercms/bundle/utils/Version.java
=> Small fixes

resources/bin/crafter.sh
Ticket craftercms/craftercms#3115
=> Fixed pre-cleanup on restore.

resources/bin/crafter.sh
Ticket craftercms/craftercms#3123
=> Fix for data dir clear on restore.

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Added support for sso logout url per headers provider
https://github.com/craftercms/craftercms/issues/2614
=> CRAFTERCMS-2614

build.gradle, dockers.gradle, resources/bin/crafter.sh
* Authoring and Delivery Tomcat images can be built now with or without profile.
* Mongo will not start if the `skipMongo` parameter is specified, even if the Crafter Profile war is present.
* The man command was removed (man pages are not being maintained currently)
=> Docker enhancements:

resources/crafter/upgrade/hooks/UpgradeHooks.groovy, resources/crafter/upgrade/hooks/UpgradeSharedConfTo3019.groovy, resources/crafter/upgrade/upgrade-target.groovy, resources/crafter/upgrade/utils/UpgradeUtils.groovy
* Upgrade hooks fixed
* Hook that upgrades the studio config now will not execute when the studio file doesn't exist.
Ticket craftercms/craftercms#3193
=> Upgrade script fixes:

resources/tomcat-config-delivery/catalina.policy, resources/tomcat-config/catalina.policy
=> Added rwd permissions for the ~/.groovy folder in catalina.policy

resources/crafter/utils/ScriptUtils.groovy
=> Fixed Groovy upgrade script issue when redirecting input.

resources/deployer/logging.xml
Ticket craftercms/craftercms#3191
=> Deployer now will also log to specific error logs for targets

resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Change Studio config and added env variables to make external DBs easier to configure.
=> Config enhancements

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Added override configuration for password requirements
https://github.com/craftercms/craftercms/issues/2364
=> CRAFTERCMS-2364

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Added sesion timeout property to overrides
https://github.com/craftercms/craftercms/issues/3240
=> CRAFTERCMS-3240

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
* Change studio.preview.createTargetUrl to /create-if-not-exists (change in Deployer).
Depends on https://github.com/craftercms/deployer/pull/137
=>  Quick fix

resources/deployer/logging.xml
* Increased logging level of AWS class that keeps spamming warning messages about profile names that contain the "profile" string.
=>  Logging enhancements

environments.gradle, resources/tomcat/ServerInfo.properties
https://github.com/craftercms/craftercms/issues/3252
=> Add file to hide Tomcat version in error pages

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Ticket craftercms/craftercms#3282
=> Added new Serverless Delivery properties in studio-config-overrides.yaml

resources/env/authoring/tomcat-config/crafter/engine/extension/logging.xml, resources/env/authoring/tomcat-config/crafter/studio/extension/logging.xml
Increased level of AWS class that spams warnings related to the profile name.
=> Logging fixes

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Ticket craftercms/craftercms#3300
=> Added new property for specifying URL format for cluster sync.

build.gradle
https://github.com/craftercms/craftercms/issues/3316
=> Fix for deployer executable jar

resources/env/authoring/tomcat-config/catalina.policy
Update JGit to v5.4.0.201906121030-r
=> Update JGit to v5.4.0.201906121030-r

resources/crafter/crafter.sh
=> Removed missing -security flags

build.gradle
=> fix binaries version issue

build.gradle
Fixed MariaDB4J poms and references
https://github.com/craftercms/craftercms/issues/3320
=> Fixed MariaDB4J poms and references

resources/bin/upgrade/hooks/PostUpgradeCompletedHook.groovy, resources/bin/upgrade/hooks/PostUpgradeHooks.groovy, resources/bin/upgrade/start-upgrade.groovy, resources/bin/upgrade/upgrade-target.groovy
Ticket craftercms/craftercms#3006
=> Fixed bundle upgrade scripts according to feedback

resources/bin/upgrade/upgrade-target.groovy
=> Remove duplicated `and`

docker/images/delivery/tomcat/Dockerfile, resources/bin/crafter.sh
Changed backup/restore to use tar (restore still uses zip for backward compatibility).
Ticket craftercms/craftercms#3416
=> Changed backup/restore to use tar

environments.gradle
Fix typo for https port when updating tomcat ports in `environments.gradle`
=> Fix typo for https port when updating tomcat ports in environments.gradle

resources/env/authoring/bin/migration/setenv.sh
https://github.com/craftercms/craftercms/issues/3468
=> Update migration script to use API 2

build.gradle, downloads.gradle
https://github.com/craftercms/craftercms/issues/3431
=> Remove all tasks related to testing

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Added configuration for user friendly description of the password requirements
https://github.com/craftercms/craftercms/issues/3314
=> CRAFTERCMS-3314

build.gradle, environments.gradle, resources/README.txt, resources/bin/grapeConfig.xml, resources/env/authoring/tomcat-config/setenv.sh, resources/env/delivery/tomcat-config/setenv.sh
- Ignore the local m2 repo & external cached grapes to avoid conflicts
- Make Tomcat use a custom Grapes config & folder
- Remove some windows specific code
https://github.com/craftercms/craftercms/issues/3326
=> Improve Groovy Grapes configuration:

resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Implemented configurable DB schema feature
https://github.com/craftercms/craftercms/issues/3503
=> CRAFTERCMS-3503

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
=> Added new default GraphQL server URL property

build.gradle
https://github.com/craftercms/craftercms/issues/3508
Depends on https://github.com/craftercms/studio/pull/1775
=> Remove VCBP from build process

environments.gradle
=> Tomcat access logs fixed to now be written to logs/tomcat

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
=> Added new target params needed for the Deployer Cloudformation target

docker/images/git_ssh_server/Dockerfile, docker/images/logrotate/Dockerfile, docker/images/logrotate/docker-entrypoint.sh, docker/images/logrotate/logrotate.tpl.conf, dockers.gradle
Ticket craftercms/craftercms#3592
=> Added Logrotate Docker image

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Updated password validation regex
https://github.com/craftercms/craftercms/issues/3530
=> [3530] [studio-ui] Password requirements should be displayed when password requirements is enabled

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Update comment for password validation regex
https://github.com/craftercms/craftercms/issues/3654
=> [3654 [[studio] Sample/default global config outdated password comments

resources/env/authoring/bin/migration/resources/content-types/controller.groovy, resources/env/authoring/bin/migration/resources/site-template/config/studio/administration/config-list.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/administration/site-config-tools.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/code-editor-config.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/environment/environment-config.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/permission-mappings-config.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/site-config.xml
=> Updated site template in migration scripts

docker/images/delivery/tomcat/Dockerfile, docker/images/profile/Dockerfile, docker/images/profile/docker-entrypoint.sh, dockers.gradle, environments.gradle
=> Added building code for a Profile Docker image.

resources/deployer/config/application.yaml, resources/deployer/config/base-target.yaml, resources/deployer/deployer.sh, resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/search/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml, resources/env/delivery/bin/crafter-setenv.sh, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/delivery/tomcat-config/crafter/search/extension/server-config.properties
Added management token configuration and enviroment variable for token
https://github.com/craftercms/craftercms/issues/3723
=> [3723] [studio] Studio UI is missing token parameter for monitoring API requests

resources/deployer/config/application.yaml, resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml, resources/env/delivery/bin/crafter-setenv.sh, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties
https://github.com/craftersoftware/craftercms/issues/18
=> Add support for encrypted configuration properties

build.gradle, downloads.gradle
https://github.com/craftercms/craftercms/issues/3679
=> Remove test-suite from bundle

resources/deployer/config/base-target.yaml, resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml, resources/env/delivery/bin/crafter-setenv.sh, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties
https://github.com/craftersoftware/craftercms/issues/22
=> Add support for Elasticsearch authentication

build.gradle
https://github.com/craftercms/craftercms/issues/3749
=> Update Elasticsearch to v6.8.6

docker/images/authoring/tomcat/docker-entrypoint.sh, docker/images/delivery/tomcat/docker-entrypoint.sh, docker/images/deployer/docker-entrypoint.sh, docker/images/profile/docker-entrypoint.sh
=> Added support for starting Docker containers on debug mode

resources/deployer/config/base-target.yaml
https://github.com/craftercms/craftercms/issues/3761
=> Update deployer config with new properties

resources/env/authoring/bin/crafter-setenv.sh
=> Adding env variable that's being used in studio-config-overrides.yaml

environments.gradle
- Upgrade binaries from groovy, tomcat, solr & elasticsearch
https://github.com/craftercms/craftercms/issues/3749
=> Fix environment tasks:

docker/images/git_ssh_server/Dockerfile, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
- Added missing region property
- Upgraded git_ssh_server Alpine to 3.10
=> Quick fixes:

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
=> Added missing comment to config property

resources/bin/upgrade/upgrade-target.groovy
=> Delete now doesn't ask for user input on non-config file deletes

downloads.gradle
=> Fixed MariaDB4j Maven download URL

resources/env/authoring/bin/migration/resources/site-template/config/engine/site-config.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/administration/site-config-tools.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/site-config.xml
=> Updated site template of migration script with latest from empty bp.

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Update headers authorization config comments
Update token comments
=> Update headers authorization config comments

build.gradle
https://github.com/craftercms/craftercms/issues/3899
=> Update tomcat version

resources/deployer/config/application.yaml, resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml, resources/env/delivery/bin/crafter-setenv.sh, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties
- Set the configuration environment for engine & studio
https://github.com/craftercms/craftercms/issues/3880
=> Add new env variable:

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Use CRAFTER_ENVIRONMENT to set active env
=> Use CRAFTER_ENVIRONMENT to set active env

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Use CRAFTER_ENVIRONMENT to set active env for develop
=> Use CRAFTER_ENVIRONMENT to set active env for develop

resources/env/authoring/bin/migration/resources/site-template/config/studio/administration/config-list.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/administration/site-config-tools.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/form-control-config/rte/rte-setup-tinymce5.xml
=> Updated migration site template.

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Update comment for staging and fix typo
=> Update comment for staging and fix typo

build.gradle
update mariadb4j version
https://github.com/craftersoftware/craftercms/issues/82
=> [82 E] [studio] Enhance MariaDB4j security

resources/bin/upgrade/hooks/v30/RecreateSolrCoresHook.groovy
https://github.com/craftercms/craftercms/issues/4100
=> Fix upgrade from 3.0.x

build.gradle, downloads.gradle
https://github.com/craftercms/craftercms/issues/3736
=> Upgrade ES v7.2.1

resources/deployer/deployer.sh
https://github.com/craftercms/craftercms/issues/4120
=> Add new config for the deployer

resources/deployer/config/base-target.yaml, resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties
https://github.com/craftercms/craftercms/issues/4119
=> Add new elasticsearch properties

environments.gradle
https://github.com/craftercms/craftercms/issues/4126
=> Fix empty folders on upgrade

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Ticket https://github.com/craftercms/craftercms/issues/4134
=> Fixed serverless properties

resources/env/authoring/bin/migration/resources/site-template/config/engine/site-config.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/context-nav/contextual-nav.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/context-nav/sidebar.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/data-sources/cmis-config.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/form-control-config/rte/rte-setup-tinymce5.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/form-control-config/rte/rte-setup.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/mime-type.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/permission-mappings-config.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/preview-tools/panel.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/site-config.xml
=> Upgraded migration site template before release

resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
https://github.com/craftercms/craftercms/issues/4178
=> Add new variables for Studio encryption

resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
=> Add new variables for Studio encryption 

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
=> Added forwarded headers property for Studio

resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties
https://github.com/craftercms/craftercms/issues/4234
=> Add new property for engine

environments.gradle, resources/env/authoring/tomcat-config/Catalina/localhost/studio.xml
Added default Tomcat context for Studio with configuration for setting `SameSite: Strict` for Studio cookies
=> Added default Tomcat context for Studio

build.gradle, environments.gradle, resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/Catalina/localhost/studio.xml, resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml, resources/env/delivery/bin/remove-site.groovy, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties, utils/pom.xml
=> Sync with support/3.1.x

environments.gradle, resources/env/authoring/tomcat-config/Catalina/localhost/studio.xml
- Added default Tomcat context for Studio with configuration for setting `SameSite: Strict` for Studio cookies
=> Added default Tomcat context for Studio:

environments.gradle, resources/env/authoring/tomcat-config/Catalina/localhost/studio.xml
=> Removed Tomcat cookie processor config

resources/env/authoring/bin/migration/resources/site-template/config/engine/proxy-config.xml, resources/env/authoring/bin/migration/resources/site-template/config/engine/site-config.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/studio_version.xml
=> Updated migration script config

resources/bin/crafter.sh, resources/env/authoring/bin/crafter-setenv.sh, resources/env/delivery/bin/crafter-setenv.sh
Ticket craftercms/craftercms#4268
=> Added env variable for backups folder

resources/deployer/config/base-target.yaml
craftercms/craftercms#4262, craftercms/craftercms#3929, craftercms/craftercms#4267
Depends on https://github.com/craftercms/deployer/pull/256
=> Update deployer configuration

resources/bin/crafter.sh
Added users backup
https://github.com/craftercms/craftercms/issues/4274
=> [4274] [craftercms] [studio] Can't restore backup because of missing crafter user

resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties
https://github.com/craftercms/craftercms/issues/4294
=> Add new properties for engine

pom.xml
https://github.com/craftercms/craftercms/issues/4272
=> Add version for new dependency

build.gradle, pom.xml
=> Replace ehcache with guava & fix build for profile

resources/bin/crafter.sh
fixed backup/restore error
https://github.com/craftercms/craftercms/issues/4308
=> [4308] [studio] Restoring a backup (with the users not backed up) fails

gradle.properties, pom-spring-boot.xml, pom.xml
https://github.com/craftercms/craftercms/issues/4334
=> Upgrade ES to 7.7.1

build.gradle, environments.gradle
https://github.com/craftercms/craftercms/issues/4345
=> Add crafter-cli to the build

resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
added socket timeout config
https://github.com/craftersoftware/craftercms/issues/183
=> [183E] [studio] Add socketTimeout=60000 to studio.db.url

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
=> Fixed typo

resources/env/authoring/tomcat-config/crafter/studio/extension/logging.xml
https://github.com/craftercms/craftercms/issues/4257
=> Change Spring Security logging level

pom-spring-boot.xml
https://github.com/craftercms/craftercms/issues/4443
=> Add new dependencies for Deployer

resources/deployer/config/base-target.yaml, resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties
=> Add new property for ES client

resources/env/authoring/bin/migration/resources/site-template/config/studio/workflow/notification-config.xml
=> Updates site template for migration

pom.xml
https://github.com/craftercms/craftercms/issues/4429
=> Added new dependency for JWT

resources/deployer/config/base-target.yaml
https://github.com/craftercms/craftercms/issues/4390
=> Add management token for Studio in the Deployer

resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
https://github.com/craftercms/craftercms/issues/4429
=> Add new properties for JWT

README.md
Fix typo and add suggestions to some wordings in readme
=> Fix typo and add suggestions to some wordings in readme

resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
=> [3.1] Updates #4581

resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
=> [develop] Updates #4581

resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties
https://github.com/craftercms/craftercms/issues/4603
=> 3.1/feature/4603

resources/deployer/deployer.sh
https://github.com/craftercms/craftercms/issues/4614
=> Fix for grapes config in Deployer

resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties
=> Add new S3 property for serverless

pom-spring-boot.xml, pom.xml
https://github.com/craftercms/craftercms/issues/4630
=> Update AWS SDK version

resources/bin/upgrade/start-upgrade.groovy
Update bundle url in start-upgrade script
=> Update bundle url in start-upgrade script

resources/bin/upgrade/start-upgrade.groovy
Update bundle url in start-upgrade script
=> [3.1.x] Update bundle url in start-upgrade script

resources/env/authoring/bin/migration/resources/site-template/config/studio/form-control-config/rte/rte-setup-tinymce5.xml, resources/env/authoring/bin/migration/resources/site-template/config/studio/permission-mappings-config.xml
=> Updated migration site template

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
=> Fix override file for studio

environments.gradle
https://github.com/craftersoftware/craftercms/issues/234
=> Fix grapes downloads

resources/deployer/config/base-target.yaml, resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/authoring/tomcat-config/crafter/search/extension/server-config.properties, resources/env/delivery/bin/crafter-setenv.sh, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/delivery/tomcat-config/crafter/search/extension/server-config.properties
craftersoftware/craftercms#246
Depends on craftercms/search#247
=> Add access token for Crafter Search

pom.xml
https://github.com/craftercms/craftercms/issues/4736
=> Refactor to remove Solr

resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties
https://github.com/craftercms/craftercms/issues/4748
=> Disable Etag filter for preview

gradle.properties, pom-spring-boot.xml, pom.xml
https://github.com/craftersoftware/craftercms/issues/252
=> Update MariaDB & MariaDB4j

resources/bin/crafter.sh, resources/bin/crafter2.sh
Remove quarantine attr for Elasticsearch files #4822
=> [develop] Remove quarantine attr for Elasticsearch files #4822

resources/bin/crafter.sh
Remove quarantine attr for Elasticsearch files #4822
=> [3.1.x] Remove quarantine attr for Elasticsearch files #4822

environments.gradle
=> Disable ml for elasticsearch

resources/deployer/config/base-target.yaml, resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties
https://github.com/craftercms/craftercms/issues/4980
=> Add global flag to enable translation support

commons.gradle
https://github.com/craftercms/craftercms/issues/4749
=> Fix for exceptions

resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties, resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties
https://github.com/craftersoftware/craftercms/issues/279
=> Add new flag for freemarker

resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
https://github.com/craftercms/craftercms/issues/5040
=> Add new env variables for JWT

resources/bin/upgrade/hooks/PostUpgradeHooks.groovy, resources/bin/upgrade/hooks/RecreateIndexesHook.groovy
https://github.com/craftercms/craftercms/issues/4982
=> Add support for upgrades from 3.1.x

deploy.gradle
=> Fixed https://github.com/craftercms/craftercms/issues/5143

resources/bin/upgrade/hooks/PostUpgradeHooks.groovy
https://github.com/craftercms/craftercms/issues/4993
=> Updates according to feedback

pom-spring-boot.xml, pom.xml
=> Update Log4j version

build.gradle
=> Update Elasticsearch version

resources/bin/crafter.sh
https://github.com/craftercms/craftercms/issues/5172
=> Added management tokens to status checks

gradle.properties, pom.xml
=> Update MariaDB4J version

README.md
Update Windows instruction
https://github.com/craftercms/craftercms/issues/5112
=> [3.1] Update Windows instruction

README.md
Update Windows instruction
https://github.com/craftercms/craftercms/issues/5112
=> [develop] Update Windows instruction

resources/deployer/deployer.sh
https://github.com/craftercms/craftercms/issues/5195
=> [5195] Fixed order of Java Opts and -jar

pom-spring-boot.xml, pom.xml
https://github.com/craftercms/craftercms/issues/5210
=> Add new versions for Elasticsearch client

build.gradle, resources/bin/upgrade/hooks/v30/RecreateSolrCoresHook.groovy, resources/bin/utils/EnvironmentUtils.groovy, resources/env/authoring/bin/migration/resources/site-template/config/studio/studio_version.xml, utils/pom.xml
=> Sync with 3.1.x

pom.xml
https://github.com/craftercms/craftercms/issues/5365
=> Upgrade Tika version

pom.xml
https://github.com/craftercms/craftercms/issues/5325
=> Add new property for studio

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
https://github.com/craftersoftware/craftercms/issues/320
=> Security refactor

resources/bin/crafter.sh
Check the Java version first, then check if JAVA_HOME is set and that it's set to the right JVM. Fixes https://github.com/craftercms/craftercms/issues/5392
Fixes: #5392
=> Check JAVA_HOME properly

resources/env/authoring/bin/crafter-setenv.sh, resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
=> Add support for cookie domain in refresh token

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
Update property and description for password requirements [#5816](https://github.com/craftercms/craftercms/issues/5816)
=> Update property and description for password requirements #5816

resources/bin/crafter.sh
https://github.com/craftercms/craftercms/issues/6029
=> Enhance `crafter.sh to address the issues listed in https://github.com/craftercms/craftercms/issues/6029

resources/env/authoring/tomcat-config/setenv.sh, resources/env/delivery/tomcat-config/setenv.sh
https://github.com/craftercms/craftercms/issues/6027
=> Prevent ESAPI logging debug/warning to stdout

resources/bin/crafter.sh
=> Fix function name collision

pom-spring-boot.xml
Spring boot spring-framework version
=> Dependencies update

pom-spring-boot.xml
Update quartz dependency to match pom.xml
=> Update dependency to match pom.xml

.github/dependabot.yml, pom-spring-boot.xml, pom.xml
=> Switched dependencies to be in the parent POMs

resources/bin/upgrade/upgrade-search.groovy
https://github.com/craftersoftware/craftercms/issues/808
=> Update upgrade-search script to use RestClient

pom.xml
https://github.com/craftercms/craftercms/issues/5977
=> Update dependencies version

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
https://github.com/craftercms/craftercms/issues/6625
Add missing duplicateTargetUrl property
=> Add missing duplicateTargetUrl property

README.md, gradle.properties, pom.xml, resources/bin/crafter.sh
https://github.com/craftercms/craftercms/issues/6490
=> Upgrade to MariaDB11

build.gradle, docker.gradle, gradle.properties, resources/docker/images/authoring/tomcat/Dockerfile, resources/docker/images/authoring/tomcat/docker-entrypoint.sh, resources/docker/images/authoring_local/tomcat/Dockerfile, resources/docker/images/authoring_local/tomcat/docker-entrypoint.sh, resources/docker/images/delivery/tomcat/Dockerfile, resources/docker/images/delivery/tomcat/docker-entrypoint.sh, resources/docker/images/deployer/Dockerfile, resources/docker/images/deployer/docker-entrypoint.sh, resources/docker/images/git_https_server/Dockerfile, resources/docker/images/git_https_server/conf/extra/httpd-ssl.conf, resources/docker/images/git_https_server/conf/extra/httpd-vhosts.conf, resources/docker/images/git_https_server/conf/httpd.conf, resources/docker/images/git_https_server/docker-entrypoint.sh, resources/docker/images/git_ssh_server/Dockerfile, resources/docker/images/git_ssh_server/docker-entrypoint.sh, resources/docker/images/git_ssh_server/no-interactive-login, resources/docker/images/logrotate/Dockerfile, resources/docker/images/logrotate/docker-entrypoint.sh, resources/docker/images/logrotate/logrotate.tpl.conf, resources/docker/images/profile/Dockerfile, resources/docker/images/profile/docker-entrypoint.sh
https://github.com/craftercms/craftercms/issues/6781
=> Added Docker image generation to the core build system.

aggregate-boms.sh, commons.gradle
craftersoftware/craftercms#742
Merge with https://github.com/craftercms/studio-ui/pull/3855
=> [742e] SBOM Generation

build.gradle, docker.gradle, gradle.properties, resources/docker/images/authoring/tomcat/Dockerfile, resources/docker/images/authoring/tomcat/docker-entrypoint.sh, resources/docker/images/authoring_local/tomcat/Dockerfile, resources/docker/images/authoring_local/tomcat/docker-entrypoint.sh, resources/docker/images/delivery/tomcat/Dockerfile, resources/docker/images/delivery/tomcat/docker-entrypoint.sh, resources/docker/images/deployer/Dockerfile, resources/docker/images/deployer/docker-entrypoint.sh, resources/docker/images/git_https_server/Dockerfile, resources/docker/images/git_https_server/conf/extra/httpd-ssl.conf, resources/docker/images/git_https_server/conf/extra/httpd-vhosts.conf, resources/docker/images/git_https_server/conf/httpd.conf, resources/docker/images/git_https_server/docker-entrypoint.sh, resources/docker/images/git_ssh_server/Dockerfile, resources/docker/images/git_ssh_server/docker-entrypoint.sh, resources/docker/images/git_ssh_server/no-interactive-login, resources/docker/images/logrotate/Dockerfile, resources/docker/images/logrotate/docker-entrypoint.sh, resources/docker/images/logrotate/logrotate.tpl.conf, resources/docker/images/profile/Dockerfile, resources/docker/images/profile/docker-entrypoint.sh
https://github.com/craftercms/craftercms/issues/6781
=> Added Docker image generation to the core build system

README.md
Add serverless environment variables in the README https://github.com/craftercms/craftercms/issues/6806
=> [develop] Add serverless environment variables in the README #6806

pom.xml, resources/deployer/logging.xml, resources/env/authoring/tomcat-config/crafter/engine/extension/logging.xml, resources/env/authoring/tomcat-config/crafter/studio/extension/logging.xml, spring-boot/pom.xml
https://github.com/craftercms/craftercms/issues/6617
=> Upgrade to AWS SDK v2
