craftercms/craftercms

resources/deployer/deployer.sh
resources/deployer/logback-spring.xml

* Added a logback-spring.xml so that changing logging can be more easy.
* All log output now will appear under the current deployment folder, instead of data, so as to keep consistency with other Crafter processes like Tomcat and Solr.

Deployer changes

---

build.gradle
environments.gradle

Gradle external process output is now redirected to a file which is "tailed" by a different thread that the one running the gradle.
`\r`does not play well with Process redirect outputstream but when saved on file (that get's converted in a `\n` by Java's internals ) it does work just fine.
Init process also won't stop if something is already cloned It will just log and carry on.

Gradle external process output is now redirected to a file

---

resources/crafter/crafter-setenv.sh
resources/crafter/crafter.sh
resources/deployer/deployer.sh

Overhaul to all process startup/stop. 
Now scripts will not only depend on the PID files but also if there's a process running on the needed port. 
The shutdown will also check that the process is actually down by using the PID and checking that Ports were free and if all of that fails a good old kill -9 will be invoked.

Should solve #826

---

resources/crafter/crafter.sh

This may be a typo. The message about where to find logs is blinking blue, making it hard to see and cut/paste. Changing it to non-blinking red like other part of the script.

Fix blinking blue message after startup

---

build.gradle

'clear' may just be a typo. Most build system uses the term 'clean'. Also, since 'clean' is already a task by itself, removing it from normal build helps speeding up development. Otherwise, we lost the benefit of incremental build.

Rename task 'clear' to 'clean' and remove from normal build.

---

resources/crafter/init-site.sh

* Did some fixes to Delivery init-site.sh script (if the repo URL is not passed it builds the URL assuming that there's a ../../crafter-auth-env folder).

Script enhances:

---

resources/crafter/crafter.bat

Windows 7,8, 8.1 might need to install this before starting up or mongodb won't startup. https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

Solves #1211 

---

build.gradle
downloads.gradle
resources/crafter/crafter.bat
resources/crafter/debug.sh
utils/src/main/java/org/craftercms/bundle/utils/actions/Download.java
utils/src/main/java/org/craftercms/bundle/utils/actions/DownloadMongoDB.java
utils/src/main/java/org/craftercms/bundle/utils/actions/DownloadMongoMSIDB.java

Solves: 1264 1268
Partially solves 1253 
Also:
* `upgrade` task will run the `update` 
* Better OS detection 
* Creating the `test-properties.properties` the file will not escape the URL
* Better support for the gradle task output console printing
* Windows Startup script for mongo will now check if the MSI is installed, if not it will download and unzip the zip version
* Download Until now can download any URL `java -jar crafter-utils.jar download URL`
Also now the unit test is not executed unless the param `-P"crafter.unittest` is set to true.
Script will get Windows build version and try to download the selenium driver for that build number (need to keep this updated)
Added: 
* `crafter.testing.chrome` which is the version of the wanted chrome driver default to `2.31`
* …

Multiple Windows Fixes

---

build.gradle

Also:
* Ignore integration-test projects
* Adds `crafter.git.shallowClone` for faster CI or testing clones this will only get the git HEAD code and will not get history or anything else use this only for testing,CI or release builds, not for actual development

Testing flag is honor again, also ignores integration-tests, `gradlew test` can be call on any supported OS 

---

resources/crafter/crafter.sh

Solves #1539
* status_mongodb now works (mismatch between help message and actual argument name.).
* status_mongodb now will check if mongo is installed print a message if not.
* status_mongodb check if MongoDB is stopped and print a message if not.
* status_mariadb will show a message if MariaDB PID is not found (is not running) instead of a `cat` file not found message.

Changes to Status of Mongodb and Mariadb

---

resources/migration/migrate.sh
resources/migration/resources/site-template/config/engine/site-config.xml

* Added search for old date patterns so that the person doing the migration can change them.
* Added flag to disable full content model type conversion for compatibility with 2.5. 
* Added code to tranlate old <i10n> Engine config properties into <targeting> properties.

Fix for 1806:

---

resources/crafter/crafter.sh
utils/pom.xml

Fixes Util version.
crafter.sh
* calling directly `start_solr` now works.
* Hardcoded version number is now dynamic.

Fix util version, Minor fixes in crafter.sh

---

resources/crafter/crafter.sh

* craftercms.sh now checks if the Solr indexes directory exists when starting up Solr, and creating it if it doesn't.
Ticket craftercms/craftercms#2143

Indexes directory is now created on startup:

---

environments.gradle
resources/crafter/init-site.bat
resources/crafter/init-site.groovy
resources/crafter/init-site.sh

* Added code to call init-site.groovy -h so that it downloads the dependencies and puts them under crafter-delivery/bin/grapes.
* The init-site.sh and init-site.bat will now call the Groovy script specifying crafter-delivery/bin/grapes as the Grapes root.
Ticket craftercms/craftercms#2169

Deploy task now downloads Grape dependencies:

---

resources/crafter/upgrade/upgrade.groovy

On full upgrade, Tomcat conf folder is now copied instead of just the erver.xml.
Ticket craftercms/craftercms#2180.

Copying now Tomcat conf folder on full upgrade.

---

resources/tomcat-config/crafter/studio/extension/studio-config-override.yaml

* Fixed SSO logout URL, default mod_auth_mellon param is ReturnTo.
* Changed {loginUrl} to {baseUrl} since in SSO it doesn't make sense to redirect to the Studio login page.
Ticket craftercms/craftercms#2500

SSO logout fixes:

---

resources/tomcat-config-delivery/catalina.policy
resources/tomcat-config/catalina.policy

Missing permissions already added to `support/3.0.x`

Fix for BouncyCastle provider permissions

---

environments.gradle
resources/env/authoring/bin/crafter-setenv.sh
resources/env/authoring/tomcat-config/setenv.sh
resources/env/delivery/bin/crafter-setenv.sh
resources/env/delivery/tomcat-config/setenv.sh

* Fixed issue with wrong ports being written to delivery setenv.sh
* Fixed ES warning that appears on startup about ignoring JAVA_OPTS
Ticket craftercms/craftercms#2896

Small fixes:

---

utils/src/main/java/org/craftercms/bundle/utils/actions/Zip.java

Ticket craftercms/craftercms#3112

Zip utility now closes the input streams correctly.

---

resources/bin/upgrade/hooks/PostUpgradeHooks.groovy

Fixed issue with upgrade embedded DB hook being called on delivery upgrade
Ticket craftercms/craftercms#3410

Fixed issue with upgrade

---

resources/bin/crafter.sh

`crafter.sh` checks port of MariaDB is being used or not before start Tomcat.
But if we use externalDb, this check is unnecessary.
For example in case of externalDb host is same as host of studio. This check cause Tomcat cannot start.

add check using external db when start tomcat

---

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml

Added studio proxy controller configuration
https://github.com/craftercms/craftercms/issues/3766

[3766] [studio-ui] Parameter "token" missing from call to /api/1/monitoring/log.json

---

resources/deployer/config/application.yaml
resources/env/authoring/bin/crafter-setenv.sh
resources/env/authoring/tomcat-config/crafter/engine/extension/server-config.properties
resources/env/authoring/tomcat-config/crafter/profile/extension/server-config.properties
resources/env/authoring/tomcat-config/crafter/search/extension/server-config.properties
resources/env/authoring/tomcat-config/crafter/social/extension/social.properties
resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
resources/env/delivery/bin/crafter-setenv.sh
resources/env/delivery/tomcat-config/crafter/engine/extension/server-config.properties
resources/env/delivery/tomcat-config/crafter/profile/extension/server-config.properties
resources/env/delivery/tomcat-config/crafter/search/extension/server-config.properties
resources/env/delivery/tomcat-config/crafter/social/extension/social.properties

Update comments for management tokens: 
- Remove comment `# Please update this per installation and provide this token to the status monitors.` and place comment in `crafter-setenv.sh` instead to make it obvious that they should only change the value there in `crafter-setenv.sh`
- Add comment `# XXX management authorization token`, where `XXX` is module name to make all files consistent
Fix typo in default value of encryption salt and key

Update comments for management tokens

---

resources/env/authoring/tomcat-config/crafter/studio/extension/studio-config-override.yaml
resources/env/delivery/bin/remove-site.groovy

- Rolledback serverless properties changes
- Delivery remove site scripts now checks if the local repo exists before trying to delete the folder
Ticket craftercms/craftercms#4197

Enhancements:

---

resources/deployer/deployer.sh

Moved -jar after JAVA_OPTS for deployer startup and shutdown, see https://github.com/craftercms/craftercms/issues/5195
https://github.com/craftercms/craftercms/issues/5195

[5195] Fixed order of Java Opts and -jar

---

resources/bin/upgrade/hooks/PostUpgradeHooks.groovy

Prevent reindex when migrating from 4.1.x
Related to https://github.com/craftercms/craftercms/issues/6503

Prevent reindex when migrating from 4.1.x

---

environments.gradle

https://github.com/craftersoftware/craftercms/issues/786
Set default OpenSearch max_clause_count to 8k

Set default OpenSearch max_clause_count to 8k

---

commons.gradle

Ensure node/yarn and project dependencies are installed before running BOM generation
craftersoftware/craftercms#742

[742e] Add CycloneDX BOM Generation Capability
